In [1]:
import numpy as np
import torch

In [11]:
x=torch.Tensor(5, 3)
print(x)
type(x)

tensor([[-4.8497e+25,  3.0660e-41, -4.2110e-01],
        [ 2.8764e-01, -8.2176e-01,  6.6495e-01],
        [-5.8148e-01,  2.7724e-01, -7.7396e-01],
        [-3.2192e-01,  5.2147e-01,  1.5160e+00],
        [-7.0754e-01,  7.1600e-01, -1.3739e+00]])


torch.Tensor

In [12]:
y=torch.rand(5,3)
print(y)
type(y)
yy=torch.randn(5,3)
print(yy)

tensor([[0.8030, 0.7206, 0.2772],
        [0.8574, 0.1423, 0.7410],
        [0.3444, 0.4226, 0.2937],
        [0.8021, 0.8285, 0.9054],
        [0.3987, 0.6365, 0.9207]])
tensor([[ 0.7635, -0.8190,  1.2075],
        [-0.5182, -0.1988, -0.4017],
        [ 0.8595,  0.0984, -0.2862],
        [-0.7460, -1.2464,  0.6963],
        [-0.9919, -0.6229, -2.3283]])


In [13]:
x=x.double()
y=y.double()
print(x)
print(y)

tensor([[-4.8497e+25,  3.0660e-41, -4.2110e-01],
        [ 2.8764e-01, -8.2176e-01,  6.6495e-01],
        [-5.8148e-01,  2.7724e-01, -7.7396e-01],
        [-3.2192e-01,  5.2147e-01,  1.5160e+00],
        [-7.0754e-01,  7.1600e-01, -1.3739e+00]], dtype=torch.float64)
tensor([[0.8030, 0.7206, 0.2772],
        [0.8574, 0.1423, 0.7410],
        [0.3444, 0.4226, 0.2937],
        [0.8021, 0.8285, 0.9054],
        [0.3987, 0.6365, 0.9207]], dtype=torch.float64)


In [21]:
x = torch.Tensor([[-0.1859,  1.3970,  0.5236],
                  [ 2.3854,  0.0707,  2.1970],
                  [-0.3587,  1.2359,  1.8951],
                  [-0.1189, -0.1376,  0.4647],
                  [-1.8968,  2.0164,  0.1092]])
y = torch.Tensor([[ 0.4838,  0.5822,  0.2755],
                  [ 1.0982,  0.4932, -0.6680],
                  [ 0.7915,  0.6580, -0.5819],
                  [ 0.3825, -1.1822,  1.5217],
                  [ 0.6042, -0.2280,  1.3210]])
print(x.size())
print(y.size())

torch.Size([5, 3])
torch.Size([5, 3])


In [37]:
z=torch.stack((x,y))
print(z.size())
print(z)
print(torch.cat((x,y),0))
print(torch.cat((x,y),1))

torch.Size([2, 5, 3])
tensor([[[-0.1859,  1.3970,  0.5236],
         [ 2.3854,  0.0707,  2.1970],
         [-0.3587,  1.2359,  1.8951],
         [-0.1189, -0.1376,  0.4647],
         [-1.8968,  2.0164,  0.1092]],

        [[ 0.4838,  0.5822,  0.2755],
         [ 1.0982,  0.4932, -0.6680],
         [ 0.7915,  0.6580, -0.5819],
         [ 0.3825, -1.1822,  1.5217],
         [ 0.6042, -0.2280,  1.3210]]])
tensor([[-0.1859,  1.3970,  0.5236],
        [ 2.3854,  0.0707,  2.1970],
        [-0.3587,  1.2359,  1.8951],
        [-0.1189, -0.1376,  0.4647],
        [-1.8968,  2.0164,  0.1092],
        [ 0.4838,  0.5822,  0.2755],
        [ 1.0982,  0.4932, -0.6680],
        [ 0.7915,  0.6580, -0.5819],
        [ 0.3825, -1.1822,  1.5217],
        [ 0.6042, -0.2280,  1.3210]])
tensor([[-0.1859,  1.3970,  0.5236,  0.4838,  0.5822,  0.2755],
        [ 2.3854,  0.0707,  2.1970,  1.0982,  0.4932, -0.6680],
        [-0.3587,  1.2359,  1.8951,  0.7915,  0.6580, -0.5819],
        [-0.1189, -0.1376,  0.4

In [38]:
print(y[4][2])
print(z[1][4][2])

tensor(1.3210)
tensor(1.3210)


In [40]:
print(x+y)
print(torch.add(x, y))
print(x.add(y))
torch.add(x,y,out=x)
print(x)

tensor([[ 0.2979,  1.9792,  0.7991],
        [ 3.4836,  0.5639,  1.5290],
        [ 0.4328,  1.8939,  1.3132],
        [ 0.2636, -1.3198,  1.9864],
        [-1.2926,  1.7884,  1.4302]])
tensor([[ 0.2979,  1.9792,  0.7991],
        [ 3.4836,  0.5639,  1.5290],
        [ 0.4328,  1.8939,  1.3132],
        [ 0.2636, -1.3198,  1.9864],
        [-1.2926,  1.7884,  1.4302]])
tensor([[ 0.2979,  1.9792,  0.7991],
        [ 3.4836,  0.5639,  1.5290],
        [ 0.4328,  1.8939,  1.3132],
        [ 0.2636, -1.3198,  1.9864],
        [-1.2926,  1.7884,  1.4302]])
tensor([[ 0.2979,  1.9792,  0.7991],
        [ 3.4836,  0.5639,  1.5290],
        [ 0.4328,  1.8939,  1.3132],
        [ 0.2636, -1.3198,  1.9864],
        [-1.2926,  1.7884,  1.4302]])


In [42]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [55]:
x=torch.rand(10,10)
y=torch.rand(2, 100)
x=x.resize_(1,100)
y=y.resize_(100,2)
torch.mm(x,y).size()

torch.Size([1, 2])

In [61]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)
print(str(type(a)),", "+str(type(b)))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'torch.Tensor'> , <class 'numpy.ndarray'>


In [62]:
a[0]+=1
print(a)
print(b)

tensor([2., 1., 1., 1., 1.])
[2. 1. 1. 1. 1.]


In [64]:
a.add_(1)
a[:]+=1
a=a.add(1)
print(a)
print(b)

tensor([8., 7., 7., 7., 7.])
[4. 3. 3. 3. 3.]


In [65]:
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [66]:
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)
x=torch.randn(5,3).to(device)
y=torch.randn(5,3, device=device)
z=x+y

cpu


In [67]:
print(z.cpu().numpy())
print(z.numpy())

[[ 1.6743596  -1.4182107  -0.28092283]
 [-0.96751153  1.3257258   0.8183414 ]
 [-2.26736    -0.34748757 -1.2308087 ]
 [ 1.8238595   0.496243    1.0237564 ]
 [-1.7586515   0.60247135  0.7176548 ]]
[[ 1.6743596  -1.4182107  -0.28092283]
 [-0.96751153  1.3257258   0.8183414 ]
 [-2.26736    -0.34748757 -1.2308087 ]
 [ 1.8238595   0.496243    1.0237564 ]
 [-1.7586515   0.60247135  0.7176548 ]]


In [70]:
x=torch.ones(2,2,requires_grad=True)
print(x)
y=x+2
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
