In [9]:
import numpy as np

a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0]=5
print(a[0], a[1], a[2])

<class 'numpy.ndarray'>
(3,)
1 2 3
5 2 3


In [17]:
a=np.zeros((2,2))
b=np.ones((1,2))
c=np.full((2,2), 7)
d=np.eye(2)
e=np.random.random((2,2))
print(a)
print(b)
print(c)
print(d)
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.14317118 0.27954819]
 [0.25267917 0.06701851]]


In [14]:
b=np.array([[1,2,3], [4,5,6]])

In [21]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2,1:3]
print(b)

print(a[0,1])
b[0,0]=77
print(a[0,1])

[[2 3]
 [6 7]]
2
77


In [23]:
row_r1=a[1,:]
row_r2=a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
col_r1=a[:, 1]
col_r2=a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


In [26]:
a=np.array([[1,2], [3,4], [5,6]])
print(a[[0,1,2], [0,1,0]])
print(np.array([a[0,0], a[1,1], a[2,0]]))

print(a[[0,0], [1,1]])
print(np.array([a[0,1], a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [27]:
a=np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b=np.array([0,2,0,1])
print(a[np.arange(4), b])
a[np.arange(4), b]+=10
print(a)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [29]:
a=np.array([[1,2], [3,4], [5,6]])
bool_idx=(a>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [34]:
x=np.array([1,2])
print(x.dtype)
y = np.array([1.0, 2.0])
print(y.dtype)
z=np.array([1,2], dtype=np.int32)
print(z.dtype)

int64
float64
int32


In [35]:
x=np.array([[1,2], [3,4]], dtype=np.float64)
y=np.array([[5,6], [7,8]], dtype=np.float64)

print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [37]:
v=np.array([9,10])
w=np.array([11,12])
print(v.dot(w))
print(np.dot(v,w))
x=np.array([[1,2], [3,4]])
print(x.dot(v))
print(np.dot(x,v))

219
219
[29 67]
[29 67]


In [39]:
y=np.array([[5,6,7], [7,8,9]])


In [40]:
x=np.array([[1,2], [3,4]])
print(np.sum(x))
print(x.T)

10
[[1 3]
 [2 4]]


In [44]:
x=np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v=np.array([1,0,1])
y=np.zeros(x.shape)

for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i,j]= x[i,j]+v[j]
        
print(y)

[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]


In [45]:
vv=np.tile(v, (4,1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
